#ifndef __COMMMON_H__
#define __COMMMON_H__
#include "base_type.h"

/* tr069 ini parameters */
#define TR069_STATUS_FIRSTBOOT 			"Tr069:FirstBoot"
#define TR069_STATUS_EVENTFLAG			"Tr069:EventFlag"
#define TR069_STATUS_REQ_QUEUE			"Tr069:RequestQueue"
#define TR069_STATUS_INFORM_PARAMS		"Tr069:InformParameters"
#define TR069_STATUS_CMDKEY			"Tr069:CommandKey"
#define TR069_STATUS_TRANSTIME			"Tr069:TransferStartTime"
#define TR069_STATUS_TRANS_COMPLETE_TIME	"Tr069:TransferCompleteTime"
#define TR069_STATUS_TRANS_RET			"Tr069:TransferResult"
#if 0
/*LAN statistics*/
#define FV_ConnectionUpTime             "LAN:Stats.ConnectionUpTime"
#define FV_TotalBytesSent             	"LAN:Stats.TotalBytesSent"
#define FV_TotalBytesReceived           "LAN:Stats.TotalBytesReceived"
#define FV_TotalPacketsSent             "LAN:Stats.TotalPacketsSent"
#define FV_TotalPacketsReceived         "LAN:Stats.TotalPacketsReceived"
#define FV_CurrentDayInterval           "LAN:Stats.CurrentDayInterval"
#define FV_CurrentDayBytesSent          "LAN:Stats.CurrentDayBytesSent"
#define FV_CurrentDayBytesReceived      "LAN:Stats.CurrentDayBytesReceived"
#define FV_CurrentDayPacketsSent        "LAN:Stats.CurrentDayPacketsSent"
#define FV_CurrentDayPacketsReceived  	"LAN:Stats.CurrentDayPacketsReceived"
#define FV_QuarterHourInterval         	"LAN:Stats.QuarterHourInterval"
#define FV_QuarterHourBytesSent         "LAN:Stats.QuarterHourBytesSent"
#define FV_QuarterHourBytesReceived     "LAN:Stats.QuarterHourBytesReceived"
#define FV_QuarterHourPacketsSent       "LAN:Stats.QuarterHourPacketsSent"
#define FV_QuarterHourPacketsReceived   "LAN:Stats.QuarterHourPacketsReceived"

/*diagnostics*/
#define FV_PingDiagState				"LAN:IPPingDiagnostics.DiagnosticsState"
#define FV_PingDiagHost					"LAN:IPPingDiagnostics.Host"
#define FV_PingDiagReptNumber			"LAN:IPPingDiagnostics.NumberOfRepetitions"
#define FV_PingDiagTimeout				"LAN:IPPingDiagnostics.Timeout"
#define FV_PingDiagDataBlockSize		"LAN:IPPingDiagnostics.DataBlockSize"
#define FV_PingDiagDSCP					"LAN:IPPingDiagnostics.DSCP"
#define FV_PingDiagSuccessCount			"LAN:IPPingDiagnostics.SuccessCount"
#define FV_PingDiagFailureCount			"LAN:IPPingDiagnostics.FailureCount"
#define FV_PingDiagAvgRespTime			"LAN:IPPingDiagnostics.AverageResponseTime"
#define FV_PingDiagMinRespTime			"LAN:IPPingDiagnostics.MinimumResponseTime"
#define FV_PingDiagMaxRespTime			"LAN:IPPingDiagnostics.MaximumResponseTime"
#define FV_TracertDiagState				"LAN:TraceRouteDiagnostics.DiagnosticsState"
#define FV_TracertDiagHost				"LAN:TraceRouteDiagnostics.Host"
#define FV_TracertDiagTimeout			"LAN:TraceRouteDiagnostics.Timeout"
#define FV_TracertDiagDataBlockSize		"LAN:TraceRouteDiagnostics.DataBlockSize"
#define FV_TracertDiagMaxHopCount		"LAN:TraceRouteDiagnostics.MaxHopCount"
#define FV_TracertDiagDSCP				"LAN:TraceRouteDiagnostics.DSCP"
#define FV_TracertDiagRespTime			"LAN:TraceRouteDiagnostics.ResponseTime"
#define FV_TracertDiagHopsNumber		"LAN:TraceRouteDiagnostics.NumberOfRouteHops"

/*X_CTC_IPTV*/
#define FV_PPPoEID            		"X_CTC_IPTV:ServiceInfo.PPPoEID"
#define FV_PPPoEPassword            	"X_CTC_IPTV:ServiceInfo.PPPoEPassword"
#define FV_UserID            		"X_CTC_IPTV:ServiceInfo.UserID"
#define FV_UserPassword            	"X_CTC_IPTV:ServiceInfo.UserPassword"
#define FV_AuthURL            		"X_CTC_IPTV:ServiceInfo.AuthURL"
#define FV_AuthURLBackup             "X_CTC_IPTV:ServiceInfo.AuthURLBackup"
#define FV_LocalUpgradeUrl           "X_CTC_IPTV:ServiceInfo.LocalUpgradeUrl"
#define FV_LogServerUrl            	"X_CTC_IPTV:StatisticConfiguration.LogServerUrl"
#define FV_LogUploadInterval            "X_CTC_IPTV:StatisticConfiguration.LogUploadInterval"
#define FV_LogRecordInterval            "X_CTC_IPTV:StatisticConfiguration.LogRecordInterval"
#define FV_StatInterval            	"X_CTC_IPTV:StatisticConfiguration.StatInterval"
#define FV_PacketsLostR1            	"X_CTC_IPTV:StatisticConfiguration.PacketsLostR1"
#define FV_PacketsLostR2            	"X_CTC_IPTV:StatisticConfiguration.PacketsLostR2"
#define FV_PacketsLostR3            	"X_CTC_IPTV:StatisticConfiguration.PacketsLostR3"
#define FV_PacketsLostR4            	"X_CTC_IPTV:StatisticConfiguration.PacketsLostR4"
#define FV_PacketsLostR5            	"X_CTC_IPTV:StatisticConfiguration.PacketsLostR5"
#define FV_BitRateR1            	"X_CTC_IPTV:StatisticConfiguration.BitRateR1"
#define FV_BitRateR2            	"X_CTC_IPTV:StatisticConfiguration.BitRateR2"
#define FV_BitRateR3            	"X_CTC_IPTV:StatisticConfiguration.BitRateR3"
#define FV_BitRateR4            	"X_CTC_IPTV:StatisticConfiguration.BitRateR4"
#define FV_BitRateR5            	"X_CTC_IPTV:StatisticConfiguration.BitRateR5"
#define FV_FramesLostR1         	"X_CTC_IPTV:StatisticConfiguration.FramesLostR1"
#define FV_FramesLostR2            	"X_CTC_IPTV:StatisticConfiguration.FramesLostR2"
#define FV_FramesLostR3            	"X_CTC_IPTV:StatisticConfiguration.FramesLostR3"
#define FV_FramesLostR4            	"X_CTC_IPTV:StatisticConfiguration.FramesLostR4"
#define FV_FramesLostR5            	"X_CTC_IPTV:StatisticConfiguration.FramesLostR5"

/*ServiceStatistics*/
#define FV_Startpoint             	"X_CTC_IPTV:ServiceStatistics.Startpoint"
#define FV_Endpoint                    	"X_CTC_IPTV:ServiceStatistics.Endpoint"
#define FV_AuthNumbers                  "X_CTC_IPTV:ServiceStatistics.AuthNumbers"
#define FV_AuthFailNumbers              "X_CTC_IPTV:ServiceStatistics.AuthFailNumbers"
#define FV_AuthFailInfo                 "X_CTC_IPTV:ServiceStatistics.AuthFailInfo"
#define FV_MultiReqNumbers              "X_CTC_IPTV:ServiceStatistics.MultiReqNumbers"
#define FV_MultiFailNumbers             "X_CTC_IPTV:ServiceStatistics.MultiFailNumbers"
#define FV_MultiFailInfo                "X_CTC_IPTV:ServiceStatistics.MultiFailInfo"
#define FV_VodReqNumbers                "X_CTC_IPTV:ServiceStatistics.VodReqNumbers"
#define FV_VodFailNumbers               "X_CTC_IPTV:ServiceStatistics.VodFailNumbers"
#define FV_VodFailInfo                  "X_CTC_IPTV:ServiceStatistics.VodFailInfo"
#define FV_HTTPReqNumbers               "X_CTC_IPTV:ServiceStatistics.HTTPReqNumbers"
#define FV_HTTPFailNumbers              "X_CTC_IPTV:ServiceStatistics.HTTPFailNumbers"
#define FV_HTTPFailInfo                 "X_CTC_IPTV:ServiceStatistics.HTTPFailInfo"
#define FV_MutiAbendNumbers             "X_CTC_IPTV:ServiceStatistics.MutiAbendNumbers"
#define FV_VODAbendNumbers              "X_CTC_IPTV:ServiceStatistics.VODAbendNumbers"
#define FV_PlayErrorNumbers             "X_CTC_IPTV:ServiceStatistics.PlayErrorNumbers"
#define FV_PlayErrorInfo                "X_CTC_IPTV:ServiceStatistics.PlayErrorInfo"
#define FV_MultiPacketsLostR1Nmb        "X_CTC_IPTV:ServiceStatistics.MultiPacketsLostR1Nmb"
#define FV_MultiPacketsLostR2Nmb        "X_CTC_IPTV:ServiceStatistics.MultiPacketsLostR2Nmb"
#define FV_MultiPacketsLostR3Nmb        "X_CTC_IPTV:ServiceStatistics.MultiPacketsLostR3Nmb"
#define FV_MultiPacketsLostR4Nmb        "X_CTC_IPTV:ServiceStatistics.MultiPacketsLostR4Nmb"
#define FV_MultiPacketsLostR5Nmb        "X_CTC_IPTV:ServiceStatistics.MultiPacketsLostR5Nmb"
#define FV_VODPacketsLostR1Nmb          "X_CTC_IPTV:ServiceStatistics.VODPacketsLostR1Nmb"
#define FV_VODPacketsLostR2Nmb          "X_CTC_IPTV:ServiceStatistics.VODPacketsLostR2Nmb"
#define FV_VODPacketsLostR3Nmb          "X_CTC_IPTV:ServiceStatistics.VODPacketsLostR3Nmb"
#define FV_VODPacketsLostR4Nmb          "X_CTC_IPTV:ServiceStatistics.VODPacketsLostR4Nmb"
#define FV_VODPacketsLostR5Nmb          "X_CTC_IPTV:ServiceStatistics.VODPacketsLostR5Nmb"
#define FV_MultiBitRateR1Nmb            "X_CTC_IPTV:ServiceStatistics.MultiBitRateR1Nmb"
#define FV_MultiBitRateR2Nmb            "X_CTC_IPTV:ServiceStatistics.MultiBitRateR2Nmb"
#define FV_MultiBitRateR3Nmb            "X_CTC_IPTV:ServiceStatistics.MultiBitRateR3Nmb"
#define FV_MultiBitRateR4Nmb            "X_CTC_IPTV:ServiceStatistics.MultiBitRateR4Nmb"
#define FV_MultiBitRateR5Nmb            "X_CTC_IPTV:ServiceStatistics.MultiBitRateR5Nmb"
#define FV_VODBitRateR1Nmb              "X_CTC_IPTV:ServiceStatistics.VODBitRateR1Nmb"
#define FV_VODBitRateR2Nmb              "X_CTC_IPTV:ServiceStatistics.VODBitRateR2Nmb"
#define FV_VODBitRateR3Nmb              "X_CTC_IPTV:ServiceStatistics.VODBitRateR3Nmb"
#define FV_VODBitRateR4Nmb              "X_CTC_IPTV:ServiceStatistics.VODBitRateR4Nmb"
#define FV_VODBitRateR5Nmb              "X_CTC_IPTV:ServiceStatistics.VODBitRateR5Nmb"
#define FV_FramesLostR1Nmb              "X_CTC_IPTV:ServiceStatistics.FramesLostR1Nmb"
#define FV_FramesLostR2Nmb              "X_CTC_IPTV:ServiceStatistics.FramesLostR2Nmb"
#define FV_FramesLostR3Nmb              "X_CTC_IPTV:ServiceStatistics.FramesLostR3Nmb"
#define FV_FramesLostR4Nmb              "X_CTC_IPTV:ServiceStatistics.FramesLostR4Nmb"
#define FV_FramesLostR5Nmb              "X_CTC_IPTV:ServiceStatistics.FramesLostR5Nmb"

//added for iptvlog upload!iptv2.2 defined this value to constant 24*3600
#define FV_IptvLogUploadInterval        "X_CTC_IPTV:IptvLogUploadInterval"

#define FV_UserToken                      "X_CTC_IPTV:UserToken"
#define FV_EPGDomain                     "X_CTC_IPTV:EPGDomain"
#define FV_EPGDomainBackup               "X_CTC_IPTV:EPGDomainBackup"
#define FV_UpgradeDomain                 "X_CTC_IPTV:UpgradeDomain"
#define FV_UpgradeDomainBackup           "X_CTC_IPTV:UpgradeDomainBackup"

/*MediaPlayer*/
#define FV_MP_Volume             "MediaPlayer:Volume"

//for local Js
#define FV_Language     "DeviceInfo:Language"
#define FV_DoubleMode   "DeviceInfo:DoubleMode"
#define FV_DisplayMode    "DeviceInfo:DisplayMode"
#define FV_VideoMode    "FV_VideoMode"
#define FV_LogDomain    "X_CTC_IPTV:StatisticConfiguration.LogServerUrl"
#define FV_LogUploadTime    "X_CTC_IPTV:IptvLogUploadInterval"
#define FV_Log    "DeviceInfo:Log"
#define FV_UpgradeStatus  "DeviceInfo:UpgradeStatus"
#define FV_StandbyStatus  "DeviceInfo:Standby"
#define FV_NetRestartStatus  "DeviceInfo:NetRestart"
#endif

#endif
